inhibit_all_warnings!
use_frameworks!

source 'git@gitee.com:vgtime/VGTSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'XYIAPKit_Example' do
  pod 'XYIAPKit', :path => '../'
  pod 'XYIAPKit/Core', :path => '../'
  pod 'XYIAPKit/iTunesReceiptVerify', :path => '../'
  pod 'XYIAPKit/UserDefaultPersistence', :path => '../'
  pod 'XYIAPKit/KeychainPersistence', :path => '../'
  target 'XYIAPKit_Tests' do
    inherit! :search_paths

    
  end
end
